### PR TITLE
fix: Check lateinit status before accessing animator

### LINKED ISSUE #7: crash by lateinit property

### PR DESCRIPTION
**Pull request by string-areeb**
Fixes #7

### CODE REVIEW

**Comment by troy379** [comment]
Nice, thank you!

**Comment by florian-do** [comment]
Hello,
Thanks for the fix, are you gonna push a new version on Gradle ?
Best regards

**Comment by troy379** [comment]
Hi @florian-do 
Sure, I will push a new version till the end of the week

**Comment by MilanMalovic** [comment]
Hi @troy379 
Will you have time to update this library soon?

**Pull request merged**
